/**
 * This file contains all the Data Transfer Object (DTO) and Command Model types
 * used throughout the application's API layer. These types are derived from the
 * core database schema types to ensure consistency and type safety between the
 * database and the API.
 *
 * DTOs (Data Transfer Objects) are used to shape the data sent in API responses.
 * Command Models represent the structure of data for creating or updating resources,
 * typically used in API request payloads.
 */

import { z } from 'zod';
import type { Enums, Tables, TablesInsert, TablesUpdate } from './db/database.types';

// --- Base Type Aliases ---

/** Base row type for the 'flashcards' table. */
type FlashcardRow = Tables<'flashcards'>;

/** Base insert type for the 'flashcards' table. */
type FlashcardInsert = TablesInsert<'flashcards'>;

/** Base row type for the 'profiles' table. */
type ProfileRow = Tables<'profiles'>;

/** Base update type for the 'profiles' table. */
type ProfileUpdate = TablesUpdate<'profiles'>;

/** Enum type for language levels. */
export type LanguageLevel = Enums<'language_level'>;

// --- Flashcard DTOs and Command Models ---

/**
 * DTO for a single flashcard item in a list.
 * Represents the data structure for the `GET /api/flashcards` response.
 * It's a subset of the full FlashcardRow.
 */
export type FlashcardListItemDto = Pick<
  FlashcardRow,
  'id' | 'front' | 'back' | 'part_of_speech' | 'leitner_box' | 'review_due_at' | 'created_at'
>;

/**
 * Command Model for creating a new flashcard manually.
 * Represents the request payload for `POST /api/flashcards`.
 * Derived from FlashcardInsert, selecting only the fields required for manual creation.
 */
export type CreateFlashcardCommand = Pick<FlashcardInsert, 'front' | 'back' | 'part_of_speech'>;

/**
 * DTO for the response after creating a flashcard.
 * Represents the data structure for the `POST /api/flashcards` success response.
 */
export type CreatedFlashcardDto = Pick<
  FlashcardRow,
  'id' | 'front' | 'back' | 'part_of_speech' | 'leitner_box' | 'review_due_at' | 'created_at'
>;

/**
 * DTO for a single, detailed flashcard view.
 * Represents the data structure for the `GET /api/flashcards/{flashcardId}` response.
 */
export type FlashcardDetailDto = FlashcardRow;

/**
 * Command Model for updating an existing flashcard.
 * Represents the request payload for `PATCH /api/flashcards/{flashcardId}`.
 * All fields are optional to allow partial updates.
 */
export type UpdateFlashcardCommand = Partial<Pick<FlashcardRow, 'front' | 'back' | 'part_of_speech'>>;

// --- AI Generation DTOs and Command Models ---

/**
 * Command Model for requesting flashcard suggestions from the AI.
 * Represents the request payload for `POST /api/ai/generate-suggestions`.
 */
export type GenerateSuggestionsCommand = {
  text: string;
  level: Extract<LanguageLevel, 'b1' | 'b2' | 'c1'>;
};

/**
 * Represents a single flashcard suggestion generated by the AI.
 * Includes a temporary client-side ID for UI management before import.
 */
export type AiSuggestion = {
  id: string; // Temporary client-side UUID
  front: string;
  back: string;
  part_of_speech: string | null;
};

/**
 * Zod schema for a single flashcard suggestion generated by the AI.
 * Used for validation of AI API responses.
 */
export const AiSuggestionSchema = z.object({
  front: z.string().describe('The front side of the flashcard (a word or phrase).'),
  back: z.string().describe('The back side of the flashcard (the translation or definition).'),
  part_of_speech: z.string().nullable().describe('The part of speech (e.g., noun, verb).'),
});

/**
 * DTO for the response containing AI-generated flashcard suggestions.
 * Represents the data structure for the `POST /api/ai/generate-suggestions` response.
 */
export type GenerateSuggestionsResponseDto = {
  suggestions: AiSuggestion[];
};

/**
 * Zod schema for the entire AI response containing flashcard suggestions.
 * Used for validation of AI API responses.
 */
export const GenerateSuggestionsResponseSchema = z.object({
  suggestions: z.array(AiSuggestionSchema).describe('An array of generated flashcard suggestions.'),
});

/**
 * Command Model for importing approved AI-generated flashcards into the database.
 * Represents the request payload for `POST /api/ai/import-flashcards`.
 */
export type ImportFlashcardsCommand = {
  flashcards: Array<Pick<FlashcardInsert, 'front' | 'back' | 'part_of_speech'>>;
  metrics: {
    generatedCount: number;
    importedCount: number;
  };
};

/**
 * DTO for the response after importing flashcards.
 * Represents the data structure for the `POST /api/ai/import-flashcards` success response.
 */
export type ImportFlashcardsResponseDto = {
  message: string;
  importedCount: number;
};

// --- Review Session DTOs and Command Models ---

/**
 * DTO for a single card presented during a review session.
 * Represents an item in the `cards` array from the `GET /api/review/session` response.
 */
export type ReviewCardDto = Pick<FlashcardRow, 'id' | 'front' | 'back' | 'part_of_speech'>;

/**
 * DTO for the entire set of cards in a review session.
 * Represents the data structure for the `GET /api/review/session` response.
 */
export type ReviewSessionDto = {
  cards: ReviewCardDto[];
};

/**
 * DTO for updating a card's review status.
 * Represents the request payload for `POST /api/review/update`.
 */
export type UpdateCardReviewDto = {
  flashcardId: string;
  knewIt: boolean;
};

/**
 * Command Model for updating a card's review status.
 * Represents the request payload for `POST /api/review/update`.
 * @deprecated Use UpdateCardReviewDto instead
 */
export type UpdateReviewStatusCommand = UpdateCardReviewDto;

// --- User Profile DTOs and Command Models ---

/**
 * DTO for pagination details included in list responses.
 */
export type PaginationDto = {
  currentPage: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
};

/**
 * DTO for the response of the paginated list of flashcards.
 * Represents the data structure for the `GET /api/flashcards` response.
 */
export type ListFlashcardsResponseDto = {
  data: FlashcardListItemDto[];
  pagination: PaginationDto;
};

/**
 * DTO for the user's profile.
 * Represents the data structure for the `GET /api/profile` response.
 */
export type UserProfileDto = ProfileRow;

/**
 * DTO for updating the user's profile.
 * Represents the request payload for `PATCH /api/profile`.
 * Currently only allows updating the default AI level.
 */
export type UpdateProfileDto = {
  default_ai_level: LanguageLevel;
};

/**
 * Command Model for updating the user's profile.
 * Contains validated data and user ID to be passed to the service layer.
 */
export type UpdateProfileCommand = {
  userId: string;
  default_ai_level: LanguageLevel;
};

// --- Authentication Types ---

/**
 * Form data for user registration.
 * Represents the structure of data collected in the registration form.
 */
export type RegisterFormData = {
  email: string;
  password: string;
};

/**
 * Validation errors for registration form fields.
 * Maps field names to their corresponding error messages.
 */
export type RegisterFormErrors = {
  email?: string;
  password?: string;
};

/**
 * Complete state of the registration form component.
 * Manages form data, validation errors, loading state, and general errors.
 */
export type RegisterFormState = {
  formData: RegisterFormData;
  errors: RegisterFormErrors;
  isLoading: boolean;
  generalError: string | null;
};

// --- Flashcard View ViewModel Types ---

/**
 * ViewModel for the FlashcardTable component state.
 * Manages the list of flashcards, pagination, loading and error states.
 */
export type FlashcardTableViewModel = {
  flashcards: FlashcardListItemDto[];
  pagination: PaginationDto;
  isLoading: boolean;
  error: string | null;
};

/**
 * Props for the FlashcardRow component.
 * Represents a single row in the flashcards table.
 */
export interface FlashcardRowProps {
  flashcard: FlashcardListItemDto;
  onUpdate: (id: string, data: UpdateFlashcardCommand) => Promise<void>;
  onDelete: (id: string) => Promise<void>;
}

/**
 * Props for the EditableCell component.
 * Manages inline editing of flashcard fields.
 */
export interface EditableCellProps {
  value: string | null;
  fieldName: keyof UpdateFlashcardCommand;
  onSave: (value: string) => Promise<void>;
  isEditable?: boolean;
}

/**
 * Local state for the EditableCell component.
 * Tracks editing mode, current value, validation errors and saving state.
 */
export interface EditableCellState {
  isEditing: boolean;
  currentValue: string;
  error: string | null;
  isSaving: boolean;
}

/**
 * Props for the ActionCell component.
 * Contains action buttons for each flashcard row.
 */
export interface ActionCellProps {
  flashcardId: string;
  onDelete: (id: string) => Promise<void>;
}

/**
 * Props for the DeleteButton component.
 * Handles flashcard deletion with confirmation dialog.
 */
export interface DeleteButtonProps {
  flashcardId: string;
  onDelete: (id: string) => Promise<void>;
  isDeleting?: boolean;
}

/**
 * Props for the Pagination component.
 * Controls page navigation in the flashcard list.
 */
export interface PaginationProps {
  currentPage: number;
  pageSize: number;
  totalItems: number;
  totalPages: number;
  onPageChange: (page: number) => void;
}

/**
 * Query parameters for flashcard list pagination and sorting.
 */
export interface FlashcardListQueryParams {
  page?: number;
  pageSize?: number;
  sortBy?: string;
  order?: 'asc' | 'desc';
}

// --- Home View ViewModel Types ---

/**
 * ViewModel for AI suggestion with editing state.
 * Extends AiSuggestion with temporary editing fields to manage inline editing
 * without mutating the original suggestion data.
 */
export interface AiSuggestionViewModel extends AiSuggestion {
  isEditing: boolean;
  tempFront: string;
  tempBack: string;
  tempPartOfSpeech: string | null;
}

/**
 * ViewModel for the manual flashcard creation form.
 * Manages form state and submission status.
 */
export interface ManualFormViewModel {
  front: string;
  back: string;
  part_of_speech: string | null;
  isSubmitting: boolean;
}

/**
 * State for AI generation functionality.
 * Manages suggestions list, loading state, and error handling.
 */
export interface AiGenerationState {
  suggestions: AiSuggestionViewModel[];
  isGenerating: boolean;
  isImporting: boolean;
  error: string | null;
}

// --- OpenRouter Service Types ---

/**
 * Configuration options for OpenRouter API completion requests.
 * Used to construct and send requests to the OpenRouter AI service.
 */
export type CompletionOptions = {
  /** System-level instructions defining the model's role and behavior */
  systemPrompt: string;
  /** User's specific query or input text */
  userPrompt: string;
  /** Name of the AI model to use (e.g., 'anthropic/claude-3.5-sonnet') */
  model: string;
  /** Zod schema defining the expected structure of the JSON response */
  responseSchema: z.ZodType;
  /** Optional model parameters for fine-tuning behavior */
  params?: {
    /** Controls randomness in responses (0.0 = deterministic, 1.0 = creative) */
    temperature?: number;
    /** Maximum number of tokens to generate in the response */
    max_tokens?: number;
  };
};
